frontend.create_book:
    path:
        - /v1/books
    controller: App\Frontend\Controller\CreateNewBookController
    methods: POST

frontend.get_books_list:
    path:
        - /v1/books
    controller: App\Frontend\Controller\GetBooksListController::getBooks
    methods: GET

